export { Hero } from './Hero/Hero';
export { About } from './About/About';
export { Services } from './Services/Services';
export { ServiceGrabAndGo } from './ServiceGrabAndGo/ServiceGrabAndGo';
export { ServiceDelivery } from './ServiceDelivery/ServiceDelivery';
export { ServiceEvents } from './ServiceEvents/ServiceEvents';
export { OurClients } from './OurClients/OurClients';
export { Advantage } from './Advantage/Advantage';
export { Community } from './Community/Community';
